### ISSUE TITLE
CO only | massive productivity?

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#127]
It comes out in the wash for the DIFF graphs, but seems really high.
Does this indicate the total carbon stock in CO nearly triples in the next 30 years?
![image](https://user-images.githubusercontent.com/3913946/149859627-613b9ac9-301f-4cf5-9bd9-7e4ca610b6b6.png)

**Comment by sbassett** [comment]
fixed here: https://tnc.box.com/s/caxu5xq9kr9lps9bz3wnc4g1yeemi81p
and c48ebe823714b3fc93a8dc77de0a446aadc1986b

**Comment by aj1s** [comment]
Initially (i.e., for the CO run in January), vegc_uptake and soilc_accum were calculated proportionally from Gross primary production (GPP), being the sum of net ecosystem exchange (NEE) and RECO (all autotrophic respiration processes).  This was an incorrect approach given as CALAND handles respiration separately from the above two parameters. 

For the corrected summary flux estimates (see https://tnc.box.com/s/caxu5xq9kr9lps9bz3wnc4g1yeemi81p
and c48ebe8), vegC_update was calculated directly from NEE summary stats, while for soilC_accum, we adopted the summary statistics used in CALAND.
