### ISSUE TITLE
LANDCAT ID as area of Rx fire for single landcat

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#141]
erroneous values for historical ambition of Rx on this land type replaced with 0.06 acres, what's the actual value?

C35059 | Woodland | Private | Prescribed_burn | 2021 | 2030 | 0.06 | 0.06 | NA | NA
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
C35059 | Woodland | Private | Prescribed_burn | 2031 | 2040 | 0.06 | 0.06 | NA | NA
C35059 | Woodland | Private | Prescribed_burn | 2041 | 2100 | 0.06 | 0.06 | NA | NA

**Comment by aj1s** [comment]
This is the only cut-paste error I'm seeing now in the revised Rx estimates. Thank you for the catch. The correct start_area and end_area for this record (LAND ID = 9509011) is 0.3170702 .
