### ISSUE TITLE
Climate Scalar Sources

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#15]
- [x] Request and Evaluate iESM output used for CALAND [scale, extent, source]
- [ ] Identify preferred climate scalar source [sbassett leaning towards relying on the iESM output used for CALALND]
- [ ] Seek feedback from TNC-Policy team
- [ ] Request permission from USCA for preferred scalar source [formal or informal modification of SOW if different]
- [ ] Develop climate scalars

In the agreement with USCA we committed to including three flavors of future climate under RCP 4.5. These flavors are based on the scenarios used in the CO Water Plan  
CALAND used one model for NPP and SOC scalars (under different RCPs)

- Are the NPP and SOC scalars sources used in CALAND applicable to and available for CO/NM? [yes, see comment from msimmond below]
- Can we request permission from USCA to do RCP4.5 and RCP8.5 instead of the three flavors of RCP 4.5?
- Are the RCPs from CMIP5 still useful or should we chose SSPs from CMIP6? If we choose to pursue CMIP6 models, we will need to confirm that the SOC and NPP variables are available at a suitable resolution.

**Comment by aj1s** [comment]
@msimmond

**Comment by msimmond** [comment]
Yes, the same method used to derive CALAND's climate change scalars (RCP 4.5 and RCP 8.5) for annual net carbon fluxes in soil and vegetation using the earth system model outputs (iESM) can be applied to CO or NM.

**Comment by SRHurteau** [comment]
I'm on it! thanks for the assignment.

**Comment by sbassett** [comment]
Sarah has recommended the use of historical, RCP 4.5, and RCP 8.5 climate trajectories in our modeling. This is a change from our proposal, so permission from the funder may be required.

Based on Sarah's guidance we will target an ensemble of 10 iESMs from CMIP5. The ideal solution is to draw annual scalars from a distribution of the 10 iESMs. Because that functionality isn't supported by CALAND and because the effort to gather the data isn't insignificant we will iterate through several alternatives requiring increasing effort (as budget allows).

1. Use NPP and shrub fraction esimates from one GCM/iESM — (canEsm as used by CALAND?)
2. Use an ensemble mean of NPP and shrub fraction from 10 IESMs/GCMs (selected based on?) paper for the NW?  (Note: Graves et al.(2020) implementation scenarios not based directly on GCMS: https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0230424.t003
3. Third draw from a distribution of NPP values from the 10 GCMs per Matt Hurteau's guidance:
```Take NPP data from 10 climate models. Use the data for each time-step to create a distribution. Sample a value from the distribution for the NPP value for that time-step and use these to create the time-series of NPP data that you need.```

**Comment by sbassett** [comment]
https://www.cesm.ucar.edu/projects/community-projects/LENS/data-sets.html
https://climatedata.ibs.re.kr/data/cesm2-lens

**Comment by sbassett** [comment]
coordinates for processing extent are not standard lat long, this workbook reverse engineers the extent coordinates used for CA and applies those same rules to CO&NM.
[ClimateExtentWorkspace.xlsx](https://github.com/TNC-NMFO/NWLAND/files/6887270/ClimateExtentWorkspace.xlsx)
