### ISSUE TITLE
lc_params_co | min.. max.. mean.. columns have same max value

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#167]
In CO the max value in the Min..., Max.. and Mean... values are all 3.589... in CA the max values in the columns are all different.

**Comment by aj1s** [comment]
Summary stats of [vegc_uptake] recalculated in 'lc_params_co' with 9c6d7afddc43e60405f98703b38ec718c5ebb04b, and in 'lc_params_nm' with 85be1d214ec34663383ccf0faac7734291c1c2c6.
