### ISSUE TITLE
plot uncertainty file not found

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#169]
```
> plot_uncertainty(
+   start_year = 2021,
+   end_year = 2050,
+   varname = "Total_CumCO2eq_all_diff",
+   ylabel = "Change from baseline in total cumulative emissions (MMT CO2-eq)",
+   file_tag = "_unc",
+   data_dir_a = "./outputs/output_co_rcp45",
+   figdirs_a = c("mean", "low", "high"),
+   scenarios_a = c("B_Current_co_rcp45_climNA_output_mean_BC1_NR120", "C_Potential_co_rcp45_climNA_output_mean_BC1_NR120", "D_Maximum_co_rcp45_climNA_output_mean_BC1_NR120"),
+   scen_labs_a = c("B_Current", "C_Potential", "D_Maximum"),
+   data_dir_b = NA, figdirs_b = NA, scenarios_b = NA, scen_labs_b = NA,
+   data_dir_c = NA, figdirs_c = NA, scenarios_c = NA, scen_labs_c = NA,
+   reg = "All_region", lt = "All_land", own="All_own"
+ )
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './outputs/output_co_rcp45/mean/All_region/All_land/All_own/All_region_All_land_All_own_Total_CumCO2eq_all_diff_output.csv': No such file or directory
```

**Comment by sbassett** [comment]
graphs and tables missing from NWLAND\outputs\output_co_rcp45
maybe I exited the unzip process early?

**Comment by sbassett** [comment]
@aj1s the output file here is missing the graphs and data: https://tnc.app.box.com/s/9mzzl57jp31jje9apv057qwc6zdgor0l/file/957999962364

co8.5 looks like all are accounted for

**Comment by aj1s** [comment]
@sbassett - The co4.5 outputs from plot_caland() are also missing on COGEOPROC. Mystifying, as I know I reviewed plots from each of the four runs last Sat. I'll look for them on my local, but in the meantime am starting plot_caland() again for co 4.5. **_Expected to finish ~ 8:45 pm_**, and I'll upload as v2.  Sorry for the trouble.

**Comment by aj1s** [comment]
@sbassett - v2 of co 4.5 now up:
https://tnc.app.box.com/s/9mzzl57jp31jje9apv057qwc6zdgor0l/file/957999962364

**Comment by aj1s** [comment]
See #170
