### ISSUE TITLE
Find all final output

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#170]
On COGEOPROC 
E:/Staging/NMFO/USCA/NWLAND/outputs/…
like: output_co_rcp45.zip? or unzipped?

**Comment by sbassett** [comment]
COGEOPROC removed from COFO, now resides in NMFO.

**Comment by aj1s** [comment]
Final outputs (including plots with uncertainty bounds) are now here: 
[...\Box\USCA Project (CO and NM)\Results\Outputs_20220515_Unc_Final.zip ](https://tnc.box.com/s/mfti0kslsbhf1nux6x01g4v03go8v8bw)
