### ISSUE TITLE
Areas by land category (initial?)

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#32]
use the "area_gis_files_new" argument that by default points to CALAND_Area_Changes_2010_to_2101.csv
when running the write inputs function, use argument land_change_method = "Landuse_Avg_Annual" which is the default

**Comment by sbassett** [comment]
This issue is chained with #30, will work on this once the annual change from Sohl is analyzed.

**Comment by sbassett** [comment]
https://github.com/TNC-NMFO/NWLAND/blob/nwland_dev/raw_data/NWLAND_Area_Changes_2016_to_2050.csv

**Comment by aj1s** [comment]
Revised to include 2015 as the base year: 

https://github.com/TNC-NMFO/NWLAND/blob/nwland_dev/raw_data/NWLAND_LandType_Areas_2015_to_2050.csv
