### ISSUE TITLE
Crosswalk between Sohl landcover classes and NWLAND classes

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#38]
Sohl Code | Sohl   Description | NWLAND   Code | NWLAND   Desc
-- | -- | -- | --
1 | Water |   |  
2 | Developed |   |  
3 | Mechanically   Disturbed National Forests |   |  
4 | Mechanically   Disturbed Other Public Lands |   |  
5 | Mechanically   Disturbed Private |   |  
6 | Mining |   |  
7 | Barren |   |  
8 | Deciduous   Forest |   |  
9 | Evergreen   Forest |   |  
10 | Mixed Forest |   |  
11 | Grassland |   |  
12 | Shrubland |   |  
13 | Cropland |   |  
14 | Hay/Pasture   Land |   |  
15 | Herbaceous   Wetland |   |  
16 | Woody Wetland |   |  
17 | Perennial   Ice/Snow |   |

**Comment by sbassett** [comment]
Sohl Code | Sohl   Description | NWLAND   Code | NWLAND   Desc
-- | -- | -- | --
1 | Water | 9000 | Water
2 | Developed | 9800 | Developed
3 | Mechanically   Disturbed National Forests | 8100 | Forest
4 | Mechanically   Disturbed Other Public Lands | 8100 | Forest
5 | Mechanically   Disturbed Private | 8100 | Forest
6 | Mining | 9800 | Developed
7 | Barren | 1000 | Barren
8 | Deciduous   Forest | 8100 | Forest
9 | Evergreen   Forest | 8100 | Forest
10 | Mixed Forest | 8100 | Forest
11 | Grassland | 4000 | Grassland
12 | Shrubland | 5000 | Shrubland
13 | Cropland | 9900 | Cultivated
14 | Hay/Pasture   Land | 9900 | Cultivated
15 | Herbaceous   Wetland | 9100 | Wetland
16 | Woody Wetland | 9200 | Riparian
17 | Perennial   Ice/Snow | 3100 | Ice
  |   | 2000 | Sparse
  |   | 3000 | Desert
  |   | 6000 | Savanna
  |   | 7000 | Meadow
  |   | 8200 | Woodland

@aj1s here is a draft crosswalk between Landcover classes.

How do we forecast landcover change rates for types that aren't in the change dataset?

Can the rate of change in Sohl's Barren be used to scale our Sparse and Desert?

Can the net change in Sohl's forest types (classes 3-5 and 8-10) be used to forecast the net change in our Forest, Woodland, and Savanna classes?

It would be interesting to see the overlay between our 2016 landcover classes and the equivalent time period for Sohl.

**Comment by aj1s** [comment]
@sbassett - This draft crosswalk reflected in file "NWLAND_LandType_Areas_2016_to_2050.csv"

**Comment by aj1s** [comment]
This draft crosswalk reflected in:

https://github.com/TNC-NMFO/NWLAND/blob/nwland_dev/raw_data/NWLAND_LandType_Areas_2015_to_2050.csv

and

https://github.com/TNC-NMFO/NWLAND/blob/nwland_dev/raw_data/NWLAND_Area_Changes_2015_to_2050.csv
