### ISSUE TITLE
Fresh marsh mucking about in write_caland_inputs()

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#50]
```
Error in `$<-.data.frame`(`*tmp*`, "lt_name", value = "Fresh_marsh") : 
  replacement has 1 row, data has 0 
4.
stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
    "replacement has %d rows, data has %d"), N, nrows), domain = NA) 
3.
`$<-.data.frame`(`*tmp*`, "lt_name", value = "Fresh_marsh") at write_caland_inputs.r#662
2.
`$<-`(`*tmp*`, "lt_name", value = "Fresh_marsh") at write_caland_inputs.r#662
1.
write_caland_inputs(c_file = "2021_05_14_carbon_input_nwland_testV.xls", 
    inputs_dir = "2021_05_14_carbon_input_nwland_testV", parameter_file = "proto_lc_params.xls", 
    scenarios_file = "proto_nwl_scenarios_v01_ha.xls", units_scenario = "ha", 
    climate_c_file = "climate_c_scalars_nmco_null_2010_2100.csv",  ...
```

**Comment by sbassett** [comment]
Commenting out the fresh marsh section seemed to resolve the problem.

**Comment by sbassett** [comment]
Commenting out this section seems to work, we'll see if there are dependencies on this section.

**Comment by aj1s** [comment]
I got through the fresh marsh section with the minimal changes below  (i.e., two lines commented out, and modified line beginning with 'delta_cult$lcatcode':

`
zero_area = diff_area_calc[diff_area_calc$start_area_ha == 0,]
diff_area_calc = diff_area_calc[diff_area_calc$start_area_ha > 0,]
delta_cult = diff_area_calc[diff_area_calc$lt_code == cult_code & diff_area_calc$reg_code == delta_code,]

delta_cult$lcat_code = delta_cult$reg_code * 100000 + delta_cult$own_code        #delta_cult$lcat_code = delta_cult$reg_code * 100000 + fresh_marsh_code * 100 + delta_cult$own_code

#delta_cult$lt_name = fresh_marsh_name
#delta_cult$lt_code = fresh_marsh_code

delta_cult[,c(8:ncol(delta_cult))] = 0.00
diff_area_calc = rbind(diff_area_calc, delta_cult)
diff_area_calc = diff_area_calc[order(diff_area_calc$lcat_code),]
```
