### ISSUE TITLE
Change NWLAND landcover type "Developed" to match CALAND "Developed_all"

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#53]
In the write_caland_inputs() function, "Developed_all" is treated differently. We want developed lands to be treated differently so need to either change the code or our data to match the code.

I vote change the data to match the code so we can make as few changes as possible to the code.

**Comment by aj1s** [comment]
See commit beeaa7f65af310e6bc1f9c89406d7577054cbf47 .   With the thought of eliminating a possible cause behind Issue #63, I did a global replace of "Developed" with "Developed_all" throughout the raw input data files imported with 2021_05_25_testingWriteInputsWithPlaceholderData_noHere.R

**Comment by aj1s** [comment]
Reverted above commit (for now) to avoid new introduced aggregation error when calling write_caland_inputs.r

**Comment by sbassett** [comment]
LandType "Developed" replaced by "Developed_all" in https://github.com/TNC-NMFO/NWLAND/commit/a4f2eb86e0ea25c440cf31828943c3f4b8a237ff, write_caland_inputs.r successfully runs, no discernable side effects.
