### ISSUE TITLE
inventory records count standardization (maybe __all__ file record count standardization)

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#60]
After uncommenting the sections that were previously producing errors (following correction of the LandCat ID key fields in the raw_data files).
```
Error in `$<-.data.frame`(`*tmp*`, "Min_Mg_ha", value = c(NA, 60.32157516,  : 
  replacement has 8036 rows, data has 7528
```

### Which of these actually need to match?

- [ ]  climate_c_scalars_nmco_null_2010_2100.csv — uses Region/LandType/Owner + Component names instead of landcat codes (13783 records)
- [ ]  fire_area_RDS-2020-0016_averageannual_2001-2100.csv  — uses Region/Owner names instead of landcat codes (680 records)
- [ ]  mortality_annual_testing.csv — uses Region/LandType/Owner names instead of landcat codes (7527 records)
- [ ]  NWLAND_Area_Changes_2015_to_2050.csv — (6359 records)
- [ ]  proto_area2001_sqm_stats.csv — uses Region/LandType/Owner names instead of landcat codes (7527 records)
- [ ]  proto_area2016_sqm_stats.csv — uses Region/LandType/Owner names instead of landcat codes (7527 records)
- [ ]  soc_tpha_2017_stats.csv — (8036 records)   Note: with this commit 61c581270fbbcaf158d124863d3cf0b9f73a13a2, soc_tpha_2017_stats.csv now has 7527 records.
- [ ]  inventory_proto_agc_tpha.csv — (6846 records)
- [ ]  inventory_proto_bgc_tpha.csv — (6846 records)
- [ ]  inventory_proto_ddc_tpha.csv —  (6846 records)
- [ ]  inventory_proto_dsc_tpha.csv — (6846 records)
- [ ]  inventory_proto_ltc_tpha.csv — (6846 records)
- [ ]  inventory_proto_usc_tpha.csv — (6846 records)

**Comment by aj1s** [comment]
Provisional conclusion:  The two original area GIS raw data files need to match each other in count, and the carbon inventories for BGC, DDC, DSC, LTC, and USC _may_ need to match w/ each other (though doubting it). Beyond that, while no additional record counts need to match, none should exceed that of the original area GIS raw data files.  Notably (and hence Issue #59 being closed), it appears the count of new area changes can be less than that of the original areas; it seems this is likely always the case, as the latter is defined by the full range of LandCat_IDs, while each projected year in the former may comprise a different subset of LandCat_IDs (b/c projected land types will shift, with only Region and Ownership modeled as static).
