### ISSUE TITLE
CALAND() test run returns Error in own_conv_df_list[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by aj1s** [TNC-NMFO/NWLAND#63]
Again test running CALAND() using this argument set:

`CALAND(scen_file="NWL_Proto_v1_Hist_protoA_hist.xls", c_file_arg = "2021_05_14_carbon_input_nwland_testAN.xls", indir = "", outdir = "", start_year = 2016, end_year = 2050, value_col_dens = 7, ADD_dens = TRUE, value_col_accum = 7, ADD_accum = TRUE, value_col_soilcon=8, ADD_soilcon = TRUE, NR_Dist = 120, WRITE_OUT_FILE = TRUE, blackC = FALSE)`

returns a subscript out of bound error. Preceding lines included for context: 
```
Starting manage c transfers
neginds for out_density_df_list manage 3 are  
neginds for out_density_df_list manage 4 are  
neginds for out_density_df_list manage 5 are  
neginds for out_density_df_list manage 6 are  
neginds for out_density_df_list manage 7 are  
neginds for out_density_df_list manage 8 are  
neginds for out_density_df_list manage 9 are  
manage carbon change is  -1148807135 
manage carbon to wood is  -394706510 
manage carbon to atmos is  0 
manage carbon to energy is  0 
manage burned carbon to atmos is  0 
manage non-burned carbon to atmos is  0 
manage negative carbon cleared is  0 
Starting fire c transfers
neginds for out_density_df_list fire 3 are  
neginds for out_density_df_list fire 4 are  
neginds for out_density_df_list fire 5 are  
neginds for out_density_df_list fire 6 are  
neginds for out_density_df_list fire 7 are  
neginds for out_density_df_list fire 8 are  
neginds for out_density_df_list fire 9 are  
fire carbon to atmosphere is  -541950759 
fire negative carbon cleared is  0 
Starting conversion c transfers
Error in own_conv_df_list[[1]] : subscript out of bounds
```

**Comment by sbassett** [comment]
error occurs on CALAND.r line 4323
```add = names(own_conv_df_list[[1]])[(skip+1):ncol(own_conv_df_list[[1]])]```

skip = 34

this section of code is only called if current_region_ID = "Ocean".
beginning on line 3675 `if(current_region_ID != "Ocean") {}` this error occurs in the following else{} section

## Do we have any ocean?

- Do CO and NM have Ocean? No, but:
- Yes, Ocean has been appended to several tables in the strategy workbook: Area_2010, annual_net_area_change, veg_climate_scalars, and soil_climate_scalars.
- Ocean has also been prepended to a few sheets in 2021_05_14_carbon_input_nwland_testB1.xls.

## Would it work to manually remove these records from these workbooks/sheets? _[ideally would prevent them from being appended in write_caland_inputs().]_

### NWL_Proto_v1_Hist_protoA_hist.xls
- [x] Area_2010
- [x] annual_net_area_change
- [x] veg_climate_scalars
- [x] soil_climate_scalars

### 2021_05_14_carbon_input_nwland_testB1.xls
- [x] sum_allorgc_2010
- [x] sum_biomassc_2010
- [x] agcmain_2010
- [x] bgcmain_2010
- [x] usc_2010
- [x] dsc_2010
- [x] ddc_2010
- [x] ltc_2010
- [x] soc_2010
- [x] vegc_uptake
- [x] soilc_accum


Checked boxes indicate records with region=Ocean have been excised.

**Comment by sbassett** [comment]
My current plan is to manually remove the "ocean" lines from the generated input files, and see if we can sidestep this problem.

This worked, issue sidestepped.

**Comment by sbassett** [comment]
The changes to the input files (removing records with region=Ocean) has produced an error earlier in the function, but it appears to be a typo. #64 
My current understanding is this error appears earlier in the function because it happens when `current_region_ID != "Ocean"` instead of in the following `else{}`.

**Comment by sbassett** [comment]
This issue may still persist when Ocean actually exists, but closing for now as this bit of code will not be encountered now that Ocean and Seagrass will no longer be added by write_caland_inputs().
