### ISSUE TITLE
Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by aj1s** [TNC-NMFO/NWLAND#68]
CALAND() line 4411:

```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

**Comment by sbassett** [comment]
I see two options:

1. Check if each data frame has the missing column and if it doesn't add it before the rbind
2. Use an alternative package that allows graceful handling of missing columns (e.g. plyr's `rbind.fill()` or dplyr's bind_rows()) - assuming the output is compatible with subsequent code (e.g. are NAs allowed?)

**Comment by sbassett** [comment]
For this loop [over region or owner?]
`ncol(conv_df_pre)` = 94
`ncol(own_conv_df_list_pre[[z]])` = 97

On antecedent successful trips through this loop both of the data frames have 94 columns.

The 'extra' columns in this version of own_conv_df_list_pre[[z]]) are:
```
row_sums_diff
row_sums
col_sums_diff
```

**Comment by aj1s** [comment]
> For this loop [over region or owner?]
> `ncol(conv_df_pre)` = 94
> `ncol(own_conv_df_list_pre[[z]])` = 97
> 
> On antecedent successful trips through this loop both of the data frames have 94 columns.
> 
> The 'extra' columns in this version of own_conv_df_list_pre[[z]]) are:
> 
> ```
> row_sums_diff
> row_sums
> col_sums_diff
> ```
As we appear to be dealing with extra, not missing, columns, we could try intersect(), as here: 
https://stackoverflow.com/questions/61120906/error-in-rbinddeparse-level-numbers-of-columns-of-arguments-do-not-matc

**Comment by sbassett** [comment]
Dropping the extra columns seems to work. The function has progressed to year 2017!
