### ISSUE TITLE
caland() — out of memory error when writing output

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#69]
Likely related to #62 

It takes over an hour to encounter this error, so it's time-consuming to reproduce.

When running CALAND(), function works until writing output.
I specify: options(java.parameters = "-d64 -Xms4g -Xmx8g" )  # originally set to "-Xmx8g" 

```
Starting change/total calcs...
Starting writing output at Fri Jun 11 13:49:24 2021 
Error: OutOfMemoryError (Java): Java heap space
In addition: There were 27 warnings (use warnings() to see them)
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  56.51363 MB
> xlcFreeMemory()
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  288.9061 MB
```

Why is the free memory capped at 288.9 MB even after calling `xlcFreeMemory()`?
I have 16 GB of RAM on my laptop where I encountered this error.

- [x] Test on machine with more RAM
- [x] Run `caland()` from the command line to free up RAM
- [ ] Try different Java settings

**Comment by sbassett** [comment]
I have reproduced this error twice now, with different Java parameters.

**Comment by sbassett** [comment]
Successful run! On workstation with 64 GB installed RAM.
options(java.parameters = "-d64 -Xms8g -Xmx64g" )  # originally set to "-Xmx8g" 

```
Starting writing output at Fri Jun 11 17:33:29 2021 
Finished writing output at Fri Jun 11 17:36:33 2021 
Finished CALAND at Fri Jun 11 17:36:33 2021 
There were 26 warnings (use warnings() to see them)
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  4634.297 MB
> xlcFreeMemory()
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  14510.24 MB
```


see a618145

**Comment by aj1s** [comment]
Initiated RStudio session with:

`options(java.parameters = "-d64 -Xms8g -Xmx64g" ) # originally set to "-Xmx8g" 
`

and attempted run of CALAND() on laptop (also with 64 GB RAM). Upon writing final outputs received:

`Error: OutOfMemoryError (Java): Java heap space `

```
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  59.94653 MB
> xlcFreeMemory()
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  453.9133 MB
```

Ended session, rebooted, and attempted again, this time making sure to set the above java parameters prior to rJava (or any other package) being loaded. Again received:

`Error: OutOfMemoryError (Java): Java heap space `


```
> xlcMemoryReport() 
Amount of free memory in the Java Virtual Machine (JVM):  301.4378 MB
> xlcFreeMemory()
> xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  305.3741 MB
```

Initiated new session with higher minimum memory setting for Java:

`options(java.parameters = "-d64 -Xms32g -Xmx64g" ) # originally set to "-Xmx8g"`

Loaded XLConnect, and looked at actualized RAM allocation:

```
> XLConnect::xlcMemoryReport() 
Amount of free memory in the Java Virtual Machine (JVM):  967.3 MB
> XLConnect::xlcFreeMemory()
> XLConnect::xlcMemoryReport()
Amount of free memory in the Java Virtual Machine (JVM):  972.1007 MB

```
Only 19% of RAM is shown as being used (via Task Manager).  Specified RAM is not being allocated to Java correctly.

**Comment by aj1s** [comment]
Running by command line yields:

`Error in '[.data.frame'(man_grass_df, , value_col_range) : undefined columns selected`

**Comment by aj1s** [comment]
Successful (full) run (!) from cmd prompt on laptop with 64gb RAM. 
options(java.parameters = "-d64 -Xms8g -Xmx64g" ) # originally set to "-Xmx8g"  

25 warnings of form:
`1: In min(mortality_targetyears[hinds]): no non-missing arguments to min; returning Inf`

As @sbassett noted, these stem from setting `forest_mort_adj_last = 2024` (not 2050) in the run file for write_calands_inputs.r.

**Comment by sbassett** [comment]
running on COGEOPROC limits memory errors because it has 265GB RAM
