### ISSUE TITLE
How are management practices applied to shrubland/savanna/woodland?

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#81]
Based on my current understanding only the Forest type has any of the forest management practices applied to it [so woodland and savanna get no Rx fire]. This needs to be confirmed in the code, but based on the lc_params.xls file, we might need to do some work to make sure we can model expected practices.

**Comment by aj1s** [comment]
Based on a surficial look at the CALAND() (w/o running so as to inspect individual dataframes, and man_area_sum.df in particular),  all evidence I see indicates that:

(1)  Rx burn is strictly a forest management practice 
(2) Savanna and woodland are subjected only to rangeland management practices (i.e., compost amendments at med_frequency (10yr) and low_frequency(30yr) intervals) that affect soil C fluxes only  
(3) Practices between Forest and  Rangeland / Cultivated are treated as mutually exclusive in area
